export const UNIVERSITIES = [
  "Acadia University",
  "Bishop's University",
  "Brandon University",
  "Brock University",
  "Cape Breton University",
  "Capilano University",
  "Carleton University",
  "Concordia University",
  "Dalhousie University",
  "Emily Carr University of Art + Design",
  "Kwantlen Polytechnic University",
  "Lakehead University",
  "Laurentian University",
  "MacEwan University",
  "McGill University",
  "McMaster University",
  "Memorial University of Newfoundland",
  "Mount Allison University",
  "Mount Royal University",
  "Nipissing University",
  "NSCAD University",
  "OCAD University",
  "Queen's University",
  "Royal Roads University",
  "Saint Mary's University",
  "Simon Fraser University",
  "St. Francis Xavier University",
  "Thompson Rivers University",
  "Toronto Metropolitan University",
  "Trent University",
  "University of Alberta",
  "University of British Columbia",
  "University of Calgary",
  "University of Guelph",
  "University of King's College",
  "University of Lethbridge",
  "University of Manitoba",
  "University of New Brunswick",
  "University of Northern British Columbia",
  "University of Ottawa",
  "University of Prince Edward Island",
  "University of Regina",
  "University of Saskatchewan",
  "University of the Fraser Valley",
  "University of Toronto",
  "University of Victoria",
  "University of Waterloo",
  "University of Windsor",
  "University of Winnipeg",
  "Université de Montréal",
  "Université Laval",
  "Université du Québec à Montréal",
  "Vancouver Island University",
  "Western University",
  "Wilfrid Laurier University",
  "York University",
];

export const FIELDS_OF_STUDY = [
  "Accounting",
  "Anthropology",
  "Architecture",
  "Art History",
  "Biochemistry",
  "Biology",
  "Biomedical Engineering",
  "Business",
  "Chemistry",
  "Civil Engineering",
  "Communications",
  "Computer Engineering",
  "Computer Science",
  "Criminology",
  "Data Science",
  "Economics",
  "Education",
  "Electrical Engineering",
  "English",
  "Environmental Science",
  "Film Studies",
  "Finance",
  "Fine Arts",
  "Geography",
  "History",
  "Human Kinetics / Kinesiology",
  "International Relations",
  "Journalism",
  "Law",
  "Linguistics",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Music",
  "Nursing",
  "Philosophy",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Health",
  "Sociology",
  "Software Engineering",
  "Statistics",
  "Theatre",
  "Undeclared",
];

export const INTERESTS = [
  "Anime",
  "Art",
  "Baking",
  "Basketball",
  "Beach",
  "Board games",
  "Campus events",
  "Cycling",
  "Coffee",
  "Cooking",
  "Design",
  "Fashion",
  "Fitness",
  "Foodie",
  "Gaming",
  "Gym",
  "Hiking",
  "Movies",
  "Music",
  "Outdoors",
  "Pets",
  "Photography",
  "Podcasts",
  "Reading",
  "Running",
  "Skiing",
  "Soccer",
  "Sports",
  "Travel",
  "TV",
  "Volunteering",
  "Yoga",
];

export const ACADEMIC_INTERESTS = [
  "Academic clubs",
  "AI / ML",
  "Case competitions",
  "Co-op",
  "Data science",
  "Entrepreneurship",
  "Exchange programs",
  "First-year support",
  "Grad school",
  "Hackathons",
  "Internships",
  "Labs",
  "Office hours",
  "Pre-law",
  "Pre-med",
  "Research",
  "Scholarships",
  "STEM",
  "Study groups",
  "Sustainability",
  "Thesis / capstone",
  "Tutoring / TA",
];

export const MAX_ONBOARDING_TAGS = 5;
